// @ts-check

/**
 * Copilot SDK Driver (entry point)
 *
 * Minimal standalone program launched by copilot_harness.cjs.  Reads
 * configuration from environment variables, delegates the full session
 * lifecycle to copilot_sdk_session.cjs, and exits with the session's exit code.
 *
 *   GH_AW_PROMPT                            — path to the prompt file
 *   COPILOT_SDK_URI                          — SDK server URI (set by the harness)
 *   COPILOT_CONNECTION_TOKEN                 — shared secret for the SDK session (set by the harness)
 *   COPILOT_MODEL                            — model override (optional)
 *   GH_AW_COPILOT_SDK_MULTI_PROVIDER_JSON   — JSON-encoded multi-provider config (required).
 *                                             Shape: { model, providers: NamedProviderConfig[], models: ProviderModelConfig[] }
 *   GH_AW_COPILOT_SDK_SERVER_ARGS           — JSON-encoded allow-tool sidecar args (set by the engine)
 *
 * The sidecar is started and stopped by the harness; the driver only opens a
 * client connection, runs the session, and exits.
 *
 * Reusable helpers live in:
 *   copilot_sdk_permissions.cjs    — permission config parsing and handler builder
 *   copilot_sdk_session.cjs        — session runner and JSONL event serialization
 *   copilot_sdk_multi_provider.cjs — multi-provider JSON parsing and validation
 */

"use strict";

const fs = require("fs");
const { runWithCopilotSDK, extractPromptFromArgs } = require("./copilot_sdk_session.cjs");
const { parsePermissionConfigFromServerArgs } = require("./copilot_sdk_permissions.cjs");
const { parseMultiProviderJson } = require("./copilot_sdk_multi_provider.cjs");

// Re-export the session and permission helpers so that existing callers that
// require("./copilot_sdk_driver.cjs") (e.g. copilot_harness.cjs) continue to work.
module.exports = { extractPromptFromArgs, runWithCopilotSDK, parsePermissionConfigFromServerArgs, parseMultiProviderJson };

// ---------------------------------------------------------------------------
// Standalone entry point
// ---------------------------------------------------------------------------

/**
 * Log a message prefixed with [copilot-sdk-driver] to stderr.
 * @param {string} msg
 */
function log(msg) {
  process.stderr.write(`[copilot-sdk-driver] ${msg}\n`);
}

/**
 * Entry point when the driver is run directly with Node:
 *   node copilot_sdk_driver.cjs
 *
 * Reads configuration from environment variables and connects to the headless
 * Copilot CLI sidecar that has already been started by copilot_harness.cjs.
 * Runs a single SDK session and exits with the session's exit code.
 * Any unhandled error causes a non-zero exit.
 */
async function main() {
  // --- Read configuration from environment ---------------------

  const promptFile = process.env.GH_AW_PROMPT;
  if (!promptFile) {
    process.stderr.write("[copilot-sdk-driver] error: GH_AW_PROMPT is not set\n");
    process.exit(1);
  }

  const sdkUri = process.env.COPILOT_SDK_URI;
  if (!sdkUri) {
    process.stderr.write("[copilot-sdk-driver] error: COPILOT_SDK_URI is not set\n");
    process.exit(1);
  }

  const connectionToken = process.env.COPILOT_CONNECTION_TOKEN;
  if (!connectionToken) {
    process.stderr.write("[copilot-sdk-driver] error: COPILOT_CONNECTION_TOKEN is required. This token is generated by copilot_harness.cjs and must be passed to the driver environment\n");
    process.exit(1);
  }

  // --- Read the prompt -------------------------------------------------

  let prompt;
  try {
    prompt = fs.readFileSync(promptFile, "utf8");
  } catch (err) {
    process.stderr.write(`[copilot-sdk-driver] error: failed to read prompt file ${promptFile}: ${err}\n`);
    process.exit(1);
  }

  log(`connecting to sidecar at ${sdkUri}`);

  // --- Resolve provider configuration from environment -----------------
  // The harness injects GH_AW_COPILOT_SDK_MULTI_PROVIDER_JSON before launching
  // this driver.  Multi-provider BYOK is the only supported mode.

  const multiProviderConfig = parseMultiProviderJson(process.env.GH_AW_COPILOT_SDK_MULTI_PROVIDER_JSON);
  if (!multiProviderConfig) {
    process.stderr.write("[copilot-sdk-driver] error: GH_AW_COPILOT_SDK_MULTI_PROVIDER_JSON is not set or invalid — " + "ensure the harness resolved multi-provider config from awf-reflect data\n");
    process.exit(1);
  }

  /** @type {import("@github/copilot-sdk").NamedProviderConfig[]} */
  const providers = multiProviderConfig.providers;
  /** @type {import("@github/copilot-sdk").ProviderModelConfig[]} */
  const sdkModels = multiProviderConfig.models;
  let model = process.env.COPILOT_MODEL || multiProviderConfig.model || undefined;
  log(`multi-provider mode: ${providers.length} providers, ${sdkModels.length} models, model=${model ?? "(env)"}`);
  for (const p of providers) {
    log(`  provider: name=${p.name} type=${p.type} baseUrl=${p.baseUrl}${p.wireApi ? ` wireApi=${p.wireApi}` : ""}`);
  }

  // --- Build permission config from sidecar server args ----------------
  // GH_AW_COPILOT_SDK_SERVER_ARGS holds the JSON-encoded --allow-tool flags
  // that the Go engine passed to the sidecar. Mirror those same rules in the
  // SDK session so the driver's onPermissionRequest handler aligns with the
  // sidecar's pre-configured allow list (e.g. shell(safeoutputs:*) for
  // workflows with safe-outputs enabled and a restricted bash allowlist).
  const permissionConfig = parsePermissionConfigFromServerArgs(process.env.GH_AW_COPILOT_SDK_SERVER_ARGS);
  if (permissionConfig) {
    if (permissionConfig.allowAllTools) {
      log("permission config: allow-all-tools (sidecar launched with --allow-all-tools)");
    } else {
      log(`permission config: ${(permissionConfig.allowedTools ?? []).length} allow-tool entries from GH_AW_COPILOT_SDK_SERVER_ARGS`);
    }
  } else {
    log("permission config: none (onPermissionRequest will use unrestricted behavior)");
  }

  // --- Run SDK session -------------------------------------------------

  const result = await runWithCopilotSDK({
    sdkUri,
    prompt,
    logger: log,
    model,
    connectionToken,
    providers,
    models: sdkModels,
    permissionConfig,
  });

  process.exit(result.exitCode);
}

if (require.main === module) {
  main().catch(err => {
    process.stderr.write(`[copilot-sdk-driver] unhandled error: ${err instanceof Error ? err.stack : String(err)}\n`);
    process.exit(1);
  });
}
